name: Benchmark Workflow

jobs:
  build-and-benchmark:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out repository code

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Setup Rust
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    # Setup Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    # Install k6
    - name: Install k6
      run: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
        echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install k6

    # Checkout your repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install NPM dependencies
    - name: Install NPM dependencies
      run: npm install

    # Run npm script
    - name: Run benchmark
      run: npm run benchmark
